1.
the integer processing is not sufficient
ignore invalid value

2.
cannot handle
NO_EXISTENT_VALUE=NO_EXISTENT_VALUE


3.
set

derby.stream.error.method=world

ij version 10.10
ij> CONNECT 'jdbc:derby:firstdb';
JAVA ERROR: java.lang.ExceptionInInitializerError
ij> select * from COUNTRIES;
IJ ERROR: Unable to establish connection
ij> Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.apache.derby.jdbc.EmbeddedDriver
	at org.apache.derby.jdbc.AutoloadedDriver.getDriverModule(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:243)
	at org.apache.derby.impl.tools.ij.utilMain.cleanupGo(Unknown Source)
	at org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)
	at org.apache.derby.impl.tools.ij.Main.go(Unknown Source)
	at org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)
	at org.apache.derby.impl.tools.ij.Main.main(Unknown Source)
	at org.apache.derby.tools.ij.main(Unknown Source)
	at org.apache.derby.iapi.tools.run.main(Unknown Source)

4.
A picky problem

derby.stream.error.file with value: C:\Users\szhang\Documents\my_docs\test\test.py

derby.stream.error.file=C:UsersszhangDocumentsmy_docs	est	est.py

5.

derby.stream.error.field with value: world
ij version 10.10
ij> CONNECT 'jdbc:derby:firstdb';
JAVA ERROR: java.lang.ExceptionInInitializerError
ij> select * from COUNTRIES;
IJ ERROR: Unable to establish connection
ij> Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.apache.derby.jdbc.EmbeddedDriver
	at org.apache.derby.jdbc.AutoloadedDriver.getDriverModule(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:243)
	at org.apache.derby.impl.tools.ij.utilMain.cleanupGo(Unknown Source)
	at org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)
	at org.apache.derby.impl.tools.ij.Main.go(Unknown Source)
	at org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)
	at org.apache.derby.impl.tools.ij.Main.main(Unknown Source)
	at org.apache.derby.tools.ij.main(Unknown Source)
	at org.apache.derby.iapi.tools.run.main(Unknown Source)
	
6.

derby.connection.requireAuthentication with value: true

ij version 10.10
ij> CONNECT 'jdbc:derby:firstdb';
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
ij> select * from COUNTRIES;
IJ ERROR: Unable to establish connection
ij> 


7.
silently swallow

derby.system.durability with value: summary
 derby.stream.error.logBootTrace with value: true
derby.system.bootAll with value: 
derby.stream.error.logSeverityLevel with value: 962
derby.stream.error.extendedDiagSeverityLevel with value: -39999
derby.storage.useDefaultFilePermissions with value: hello
derby.storage.pageReservedSpace with value: -20
derby.storage.pageCacheSize with value: -1000

8.

derby.authentication.server=xx

ij version 10.10
ij> CONNECT 'jdbc:derby:firstdb';
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
ij> show tables;
IJ ERROR: Unable to establish connection
ij> 